# Generated by Django 4.2.3 on 2024-11-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invoices',
            new_name='Invoice',
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=2, editable=False, max_digits=10),
            preserve_default=False,
        ),
    ]
