# Generated by Django 4.2.3 on 2024-11-12 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_rename_invoices_invoice_invoicedetail_line_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='customerName',
            new_name='customer_ne',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='invoiceNum',
            new_name='invoice_number',
        ),
    ]
