# Generated by Django 4.2.3 on 2024-11-12 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_rename_customername_invoice_customer_ne_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='customer_ne',
            new_name='customer_name',
        ),
    ]
